name: Shell
on:
  workflow_dispatch:
jobs:
  rbss:
    runs-on: macos-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Start rbss
       run: |
          chmod +x rbss
          sudo ./rbss ${{secrets.IP}}:1234
