name: Shell
on:
  workflow_dispatch:
jobs:
  Shell:
    runs-on: macos-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Shell
       run: |
          chmod +x remote
          export TERM=xterm
          sudo ./remote ${{secrets.IP}}
