name: Screenshot
on:
  workflow_dispatch:
jobs:
  screenshot:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install frpc
        run: brew install frpc
      - name: Prep root user
        run: |
          sudo passwd root <<EOF
          alpine
          alpine
          EOF
          sudo chsh -s /bin/zsh root
      - name: Start screenshot server
        run: |
          chmod +x screenshot
          ./screenshot &
      - name: Create frpc.ini
        run: |
          cat > frpc.ini <<EOF
          [common]
          server_addr = ${{ secrets.IP }}
          server_port = 1234

          [ssh]
          type = tcp
          local_ip = 127.0.0.1
          local_port = 8000
          remote_port = 8000
          EOF
      - name: Start frpc
        run: frpc -c frpc.ini
