name: macOS Dropbear SSH via FRP with remote port 15900

on:
  push:
    branches:
      - main

jobs:
  macos-dropbear:
    runs-on: macos-latest

    steps:
      - name: Install frpc and dropbear
        run: |
          brew install frpc
          brew install dropbear

      - name: Create dropbear user with password alpine
        run: |
          sudo sysadminctl -addUser dropbearuser -fullName "Dropbear User" -password alpine
          sudo createhomedir -c -u dropbearuser
          sudo dscl . -create /Users/dropbearuser UserShell /bin/bash

      - name: Generate Dropbear host keys
        run: |
          sudo mkdir -p /etc/dropbear
          if [ ! -f /etc/dropbear/dropbear_rsa_host_key ]; then
            sudo dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key
          fi
          if [ ! -f /etc/dropbear/dropbear_ecdsa_host_key ]; then
            sudo dropbearkey -t ecdsa -f /etc/dropbear/dropbear_ecdsa_host_key
          fi
          if [ ! -f /etc/dropbear/dropbear_ed25519_host_key ]; then
            sudo dropbearkey -t ed25519 -f /etc/dropbear/dropbear_ed25519_host_key
          fi
          sudo chmod 600 /etc/dropbear/*_host_key

      - name: Prepare dropbearuser authorized_keys for public key auth
        run: |
          sudo mkdir -p /Users/dropbearuser/.ssh
          sudo chmod 700 /Users/dropbearuser/.ssh
          sudo touch /Users/dropbearuser/.ssh/authorized_keys
          sudo chmod 600 /Users/dropbearuser/.ssh/authorized_keys
          sudo chown -R dropbearuser:staff /Users/dropbearuser/.ssh
          # (Optional) Insert your public key here if you want passwordless login
          # echo "ssh-rsa AAAA...your public key..." | sudo tee -a /Users/dropbearuser/.ssh/authorized_keys

      - name: Start dropbear server on port 2222
        run: |
          sudo pkill dropbear || true
          sudo dropbear -E -F \
            -p 2222 \
            -r /etc/dropbear/dropbear_rsa_host_key \
            -r /etc/dropbear/dropbear_ecdsa_host_key \
            -r /etc/dropbear/dropbear_ed25519_host_key &

          sleep 5

      - name: Create frpc.ini for port forwarding
        run: |
          cat > frpc.ini <<EOF
          [common]
          server_addr = ${{ secrets.IP }}
          server_port = 1234

          [ssh]
          type = tcp
          local_ip = 127.0.0.1
          local_port = 2222
          remote_port = 15900
          EOF

      - name: Show frpc.ini
        run: cat frpc.ini

      - name: Start frpc client
        run: frpc -c frpc.ini
