name: macOS Dropbear SSH via FRP with remote port 15900

on:
  push:
    branches:
      - main

jobs:
  macos-dropbear:
    runs-on: macos-latest

    steps:
      - name: Install frpc and dropbear
        run: |
          brew install frpc
          brew install dropbear

      - name: Create dropbear user with password alpine
        run: |
          sudo sysadminctl -addUser dropbearuser -fullName "Dropbear User" -password alpine
          sudo createhomedir -c -u dropbearuser

      - name: Generate dropbear RSA host key (if not exists)
        run: |
          sudo mkdir -p /etc/dropbear
          if [ ! -f /etc/dropbear/dropbear_rsa_host_key ]; then
            sudo dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key
          fi

      - name: Start dropbear server
        run: |
          sudo pkill dropbear || true
          sudo dropbear -E -F -p 2222 -r /etc/dropbear/dropbear_rsa_host_key &
          sleep 5

      - name: Create frpc.ini
        run: |
          cat > frpc.ini <<EOF
          [common]
          server_addr = ${{ secrets.IP }}
          server_port = 1234

          [ssh]
          type = tcp
          local_ip = 127.0.0.1
          local_port = 2222
          remote_port = 15900
          EOF

      - name: Show frpc.ini
        run: cat frpc.ini

      - name: Start frpc
        run: frpc -c frpc.ini
