name: Setup Dropbear SSH with FRP reverse tunnel on macOS runner

on:
  push:
    branches:
      - main
  workflow_dispatch:   # manual trigger

jobs:
  dropbear-ssh:
    runs-on: macos-latest

    steps:
      - name: Install frpc and dropbear
        run: |
          brew install frpc dropbear

      - name: Create frpc.yaml config
        run: |
          cat > frpc.yaml <<EOF
          common:
            server_addr: ${{ secrets.IP }}
            server_port: 1234

          ssh:
            type: tcp
            local_ip: 127.0.0.1
            local_port: 2222
            remote_port: 2222
          EOF

      - name: Show frpc.yaml
        run: cat frpc.yaml

      - name: Start Dropbear SSH server and frpc client
        run: |
          nohup dropbear -p 2222 > dropbear.log 2>&1 &
          sleep 3
          frpc -c frpc.yaml
