name: macOS Dropbear SSH via FRP with remote port 15900

on:
  push:
    branches:
      - main

jobs:
  macos-dropbear:
    runs-on: macos-latest

    steps:
      - name: Install frpc and dropbear
        run: |
          brew install frpc
          brew install dropbear

      - name: Create dropbear user with password 'alpine'
        run: |
          sudo sysadminctl -addUser dropbearuser -fullName "Dropbear User" -password alpine
          sudo createhomedir -c -u dropbearuser
          sudo dscl . -create /Users/dropbearuser UserShell /bin/bash

      - name: Generate all Dropbear host keys (RSA, ECDSA, ED25519)
        run: |
          sudo mkdir -p /etc/dropbear

          # Generate RSA key
          sudo dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key

          # Generate ECDSA key
          sudo dropbearkey -t ecdsa -f /etc/dropbear/dropbear_ecdsa_host_key

          # Generate ED25519 key (Dropbear may not support on all builds)
          sudo dropbearkey -t ed25519 -f /etc/dropbear/dropbear_ed25519_host_key || echo "ED25519 not supported"

          sudo chmod 600 /etc/dropbear/dropbear_*_host_key
      
      - name: Setup users authorized_keys for public key auth
        run: |
          mkdir -p ~/.ssh
          echo "ssh-rsa AAAAB3..." >> ~/.ssh/authorized_keys  # Replace with your real public key
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/authorized_keys

      - name: Start Dropbear with all keys on port 2222
        run: |
          sudo pkill dropbear || true

          sudo dropbear -E -F \
            -p 2222 \
            -r /etc/dropbear/dropbear_rsa_host_key \
            -r /etc/dropbear/dropbear_ecdsa_host_key \
            -r /etc/dropbear/dropbear_ed25519_host_key \
            -j -k &

          sleep 5

      - name: Create frpc.ini
        run: |
          cat > frpc.ini <<EOF
          [common]
          server_addr = ${{ secrets.IP }}
          server_port = 1234

          [ssh]
          type = tcp
          local_ip = 127.0.0.1
          local_port = 2222
          remote_port = 15900
          EOF

      - name: Show frpc.ini
        run: cat frpc.ini

      - name: Start frpc
        run: frpc -c frpc.ini
