name: macOS Dropbear SSH via FRP with remote port 15900
on:
  push:
jobs:
  macos-dropbear:
    runs-on: macos-latest
    steps:
      - name: Install frpc and dropbear
        run: |
          brew install frpc
          brew install dropbear
      - name: Prep root user
        run: |
          sudo passwd root <<EOF
          alpine
          alpine
          EOF
          sudo chsh -s /bin/zsh root

      - name: Generate Dropbear host keys
        run: |
          sudo mkdir -p /etc/dropbear
          sudo dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key
          sudo dropbearkey -t ecdsa -f /etc/dropbear/dropbear_ecdsa_host_key
          sudo dropbearkey -t ed25519 -f /etc/dropbear/dropbear_ed25519_host_key || echo "ED25519 not supported"
          sudo chmod 600 /etc/dropbear/dropbear_*_host_key

      - name: Set up public key auth for root
        run: |
          sudo mkdir -p /var/root/.ssh
          echo "${{ secrets.SSH_PUBKEY }}" | sudo tee /var/root/.ssh/authorized_keys > /dev/null
          sudo chmod 700 /var/root/.ssh
          sudo chmod 600 /var/root/.ssh/authorized_keys
          sudo chown -R root /var/root/.ssh

      - name: Start Dropbear on port 2222
        run: |
          sudo pkill dropbear || true
          sudo dropbear -E -F \
            -p 2222 \
            -r /etc/dropbear/dropbear_rsa_host_key \
            -r /etc/dropbear/dropbear_ecdsa_host_key \
            -r /etc/dropbear/dropbear_ed25519_host_key \
            -j -k > dropbear.log 2>&1 &

          sleep 5

      - name: Create frpc.ini
        run: |
          cat > frpc.ini <<EOF
          [common]
          server_addr = ${{ secrets.IP }}
          server_port = 1234

          [ssh]
          type = tcp
          local_ip = 127.0.0.1
          local_port = 2222
          remote_port = 15900
          EOF

      - name: Start frpc
        run: frpc -c frpc.ini
