name: SSH Tunnel with frpc on macOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ssh-tunnel:
    runs-on: macos-latest
    steps:
      - name: Install frpc via Homebrew
        run: |
          brew update
          brew install frpc
          frpc --version

      - name: Enable Remote Login (sshd) and start sshd on port 2222
        run: |
          echo "Enabling Remote Login (sshd)..."
          sudo systemsetup -setremotelogin on

          echo "Stopping existing sshd if running..."
          sudo launchctl unload /System/Library/LaunchDaemons/ssh.plist || true

          echo "Starting sshd on port 2222..."
          sudo /usr/sbin/sshd -p 2222 -D &
          sleep 5

          echo "Check sshd listening on port 2222:"
          lsof -iTCP:2222 -sTCP:LISTEN || echo "sshd not listening!"

      - name: Create frpc config file
        run: |
          cat > frpc.ini <<EOF
          [common]
          server_addr = ${{ secrets.IP }}
          server_port = 1234

          [ssh]
          type = tcp
          local_ip = 127.0.0.1
          local_port = 2222
          remote_port = 2222
          EOF

          echo "frpc.ini content:"
          cat frpc.ini

      - name: Start frpc client with config
        run: |
          echo "Starting frpc..."
          frpc -c frpc.ini &

          sleep 5
          ps aux | grep frpc

      - name: Show network listeners (debug)
        run: |
          netstat -anv | grep LISTEN

      - name: Show current ssh config and users (debug)
        run: |
          sudo cat /etc/ssh/sshd_config
          dscl . list /Users

      - name: Show last lines of frpc log if any
        run: |
          if [ -f frpc.log ]; then
            tail -20 frpc.log
          else
            echo "No frpc.log found"
          fi
