name: SSH Tunnel with Dropbear and frpc

on:
  push:
  workflow_dispatch:

jobs:
  ssh-tunnel:
    runs-on: macos-latest
    steps:
      - name: Install dropbear and frpc
        run: |
          brew install dropbear frpc

      - name: Generate dropbear host keys
        run: |
          sudo mkdir -p /etc/dropbear
          sudo dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key
          sudo dropbearkey -t ecdsa -f /etc/dropbear/dropbear_ecdsa_host_key
          sudo dropbearkey -t ed25519 -f /etc/dropbear/dropbear_ed25519_host_key

      - name: Start dropbear SSH server
        run: |
          sudo dropbear -p 2222 \
            -r /etc/dropbear/dropbear_rsa_host_key \
            -c /etc/dropbear/dropbear_ecdsa_host_key \
            -y /etc/dropbear/dropbear_ed25519_host_key \
            -E -F &
          sleep 5
          echo "Dropbear processes:"
          ps aux | grep dropbear
          echo "Checking port 2222 listener:"
          lsof -iTCP:2222 -sTCP:LISTEN || echo "Nothing listening on 2222"

      - name: Create frpc.ini config using echo
        run: |
          echo "[common]\nserver_addr = ${{ secrets.IP }}\nserver_port = 1234\n\n[ssh]\ntype = tcp\nlocal_ip = 127.0.0.1\nlocal_port = 2222\nremote_port = 2222" > frpc.ini
          echo "=== frpc.ini contents ==="
          cat frpc.ini

      - name: Start frpc client
        run: |
          frpc -c frpc.ini
