name: Dropbear SSH + frpc with Full Debug

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ssh-tunnel:
    runs-on: macos-latest

    steps:
      - name: Install frpc and dropbear
        run: |
          brew install frpc dropbear

      - name: Verify dropbear installation
        run: |
          echo "Dropbear path:"
          which dropbear
          echo "Dropbear version and help:"
          dropbear -h || echo "dropbear -h failed"

      - name: Create frpc.ini config
        run: |
          cat > frpc.ini <<EOF
          [common]
          server_addr = ${{ secrets.IP }}
          server_port = 1234

          [ssh]
          type = tcp
          local_ip = 127.0.0.1
          local_port = 2222
          remote_port = 2222
          EOF
          echo "Created frpc.ini:"
          cat frpc.ini

      - name: Attempt 1: Run dropbear in foreground to see errors (timeout 15s)
        run: |
          timeout 15 dropbear -p 2222
        continue-on-error: true

      - name: Check if port 2222 is listening after attempt 1
        run: |
          lsof -iTCP:2222 -sTCP:LISTEN || echo "Nothing listening on 2222"

      - name: Attempt 2: Run dropbear in background with logs
        run: |
          dropbear -p 2222 -E -F > dropbear.log 2>&1 &
          sleep 5
          echo "Dropbear processes:"
          ps aux | grep dropbear
          echo "Port 2222 listening check:"
          lsof -iTCP:2222 -sTCP:LISTEN || echo "Nothing listening on 2222"
          echo "Dropbear logs:"
          cat dropbear.log

      - name: Start frpc client to create reverse ssh tunnel
        run: |
          frpc -c frpc.ini
