name: Dropbear SSH Tunnel on macOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ssh-tunnel:
    runs-on: macos-latest
    steps:
      - name: Install dropbear and frpc via Homebrew
        run: |
          brew update
          brew install dropbear frpc
          dropbear -h
          frpc --version

      - name: Generate dropbear host keys if missing
        run: |
          if [ ! -f /usr/local/etc/dropbear/dropbear_rsa_host_key ]; then
            echo "Generating dropbear RSA host key..."
            dropbearkey -t rsa -f /usr/local/etc/dropbear/dropbear_rsa_host_key
          fi
          if [ ! -f /usr/local/etc/dropbear/dropbear_ed25519_host_key ]; then
            echo "Generating dropbear ED25519 host key..."
            dropbearkey -t ed25519 -f /usr/local/etc/dropbear/dropbear_ed25519_host_key
          fi

      - name: Start dropbear on port 2222
        run: |
          echo "Starting dropbear on port 2222..."
          # Kill any existing dropbear to avoid conflicts
          pkill dropbear || true

          # Start dropbear in background with logs
          nohup dropbear -p 2222 -r /usr/local/etc/dropbear/dropbear_rsa_host_key -r /usr/local/etc/dropbear/dropbear_ed25519_host_key > dropbear.log 2>&1 &

          sleep 5

          echo "Dropbear processes:"
          ps aux | grep dropbear | grep -v grep

          echo "Check port 2222 listening:"
          lsof -iTCP:2222 -sTCP:LISTEN || echo "Nothing listening on 2222"

          echo "Dropbear log tail:"
          tail -20 dropbear.log

      - name: Create frpc config file
        run: |
          cat > frpc.ini <<EOF
          [common]
          server_addr = ${{ secrets.IP }}
          server_port = 1234

          [ssh]
          type = tcp
          local_ip = 127.0.0.1
          local_port = 2222
          remote_port = 2222
          EOF

          echo "frpc.ini content:"
          cat frpc.ini

      - name: Start frpc client
        run: |
          pkill frpc || true
          frpc -c frpc.ini &
          sleep 5
          echo "frpc processes:"
          ps aux | grep frpc

      - name: s
        run: |
          netstat -anv | grep LISTEN
          echo "--- Dropbear log tail ---"
          tail -20 dropbear.log
