name: Run dropbear SSH with frp

on:
  push:
  workflow_dispatch:

jobs:
  ssh-tunnel:
    runs-on: macos-latest
    steps:
      - name: Install dropbear and frp
        run: |
          brew install dropbear frpc

      - name: Generate dropbear host keys
        run: |
          mkdir -p /usr/local/etc/dropbear
          dropbearkey -t rsa -f /usr/local/etc/dropbear/dropbear_rsa_host_key
          dropbearkey -t dss -f /usr/local/etc/dropbear/dropbear_dss_host_key
          dropbearkey -t ecdsa -f /usr/local/etc/dropbear/dropbear_ecdsa_host_key
          dropbearkey -t ed25519 -f /usr/local/etc/dropbear/dropbear_ed25519_host_key

      - name: Start dropbear SSH server
        run: |
          dropbear -p 2222 -r /usr/local/etc/dropbear/dropbear_rsa_host_key -d /usr/local/etc/dropbear/dropbear_dss_host_key -c /usr/local/etc/dropbear/dropbear_ecdsa_host_key -y /usr/local/etc/dropbear/dropbear_ed25519_host_key -E -F &
          sleep 5
          lsof -iTCP:2222 -sTCP:LISTEN

      - name: Create frpc.ini file
        run: |
          cat > frpc.ini <<EOF
          [common]
          server_addr = ${{ secrets.IP }}
          server_port = 1234

          [ssh]
          type = tcp
          local_ip = 127.0.0.1
          local_port = 2222
          remote_port = 2222
          EOF
          cat frpc.ini

      - name: Run frpc
        run: |
          ./frpc -c frpc.ini
