name: macOS Dropbear SSH via FRP with remote port 15900

on:
  push:
    branches:
      - main

jobs:
  macos-dropbear:
    runs-on: macos-latest

    steps:
      - name: Install frpc and dropbear
        run: |
          brew install frpc
          brew install dropbear

      - name: Disable Spotlight indexing
        run: sudo mdutil -i off -a

      - name: Create dropbear user and home
        run: |
          sudo dscl . -create /Users/dropbearuser
          sudo dscl . -create /Users/dropbearuser UserShell /bin/bash
          sudo dscl . -create /Users/dropbearuser RealName "Dropbear User"
          sudo dscl . -create /Users/dropbearuser UniqueID 1002
          sudo dscl . -create /Users/dropbearuser PrimaryGroupID 80
          sudo dscl . -create /Users/dropbearuser NFSHomeDirectory /Users/dropbearuser
          sudo dscl . -passwd /Users/dropbearuser dropbearpass
          sudo createhomedir -c -u dropbearuser > /dev/null

      - name: Generate dropbear keys (if not existing)
        run: |
          sudo mkdir -p /etc/dropbear
          sudo dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key || true
          sudo dropbearkey -t dss -f /etc/dropbear/dropbear_dss_host_key || true

      - name: Start dropbear server
        run: |
          sudo dropbear -E -F -p 2222 -r /etc/dropbear/dropbear_rsa_host_key &
          sleep 5

      - name: Create frpc.ini
        run: |
          cat > frpc.ini <<EOF
          [common]
          server_addr = ${{ secrets.IP }}
          server_port = 1234

          [ssh]
          type = tcp
          local_ip = 127.0.0.1
          local_port = 2222
          remote_port = 15900
          EOF

      - name: Show frpc.ini
        run: cat frpc.ini

      - name: Start frpc
        run: frpc -c frpc.ini
