name: Dropbear SSH + frp reverse tunnel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ssh-tunnel:
    runs-on: macos-latest

    steps:
      - name: Install frpc and dropbear
        run: |
          brew install frpc dropbear

      - name: Create frpc.ini config
        run: |
          cat > frpc.ini <<EOF
          [common]
          server_addr = ${{ secrets.IP }}
          server_port = 1234

          [ssh]
          type = tcp
          local_ip = 127.0.0.1
          local_port = 2222
          remote_port = 2222
          EOF

      - name: Show frpc.ini
        run: cat frpc.ini

      - name: Start Dropbear SSH server and frpc client
        run: |
          nohup dropbear -p 2222 > dropbear.log 2>&1 &
          sleep 3
          frpc -c frpc.ini
