name: Reverse HTTP Tunnel with Homebrew

on:
  workflow_dispatch:

jobs:
  tunnel:
    runs-on: macos-latest
    steps:
      - name: Start simple HTTP server
        run: |
          mkdir -p demo
          echo "<h1>Hello from GitHub Actions</h1>" > demo/index.html
          cd demo
          python3 -m http.server 8000 &
          echo "HTTP server running on port 8000"

      - name: Install frpc via Homebrew
        run: |
          brew update
          brew install frpc

      - name: Create frpc.ini config safely
        run: |
          echo "[common]" > frpc.ini
          echo "server_addr = ${{ secrets.IP }}" >> frpc.ini
          echo "server_port = 1234" >> frpc.ini
          echo "" >> frpc.ini
          echo "[http-demo]" >> frpc.ini
          echo "type = tcp" >> frpc.ini
          echo "local_ip = 127.0.0.1" >> frpc.ini
          echo "local_port = 8000" >> frpc.ini
          echo "remote_port = 9000" >> frpc.ini

      - name: Print frpc.ini content
        run: |
          echo "===== frpc.ini ====="
          cat frpc.ini
          echo "===================="

      - name: Run frpc client
        run: |
          frpc -c frpc.ini
