name: macOS VNC with FRPC Tunnel

on: [push]

jobs:
  vnc-frp-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install frpc via Homebrew
        run: |
          brew update
          brew install frpc
          frpc --version

      - name: Setup Screen Sharing PPPC profile
        run: |
          PROFILE_UUID=$(uuidgen)
          PAYLOAD_UUID=$(uuidgen)

          cat > screensharing-pppc.mobileconfig <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
            "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>PayloadContent</key>
            <array>
              <dict>
                <key>PayloadType</key>
                <string>com.apple.TCC.configuration-profile-policy</string>
                <key>PayloadVersion</key>
                <integer>1</integer>
                <key>PayloadIdentifier</key>
                <string>com.example.screensharing.pppc</string>
                <key>PayloadUUID</key>
                <string>$PAYLOAD_UUID</string>
                <key>PayloadEnabled</key>
                <true/>
                <key>PayloadDisplayName</key>
                <string>Screen Sharing Permissions</string>
                <key>Services</key>
                <dict>
                  <key>com.apple.screensharing.agent</key>
                  <dict>
                    <key>IdentifierType</key>
                    <string>bundleID</string>
                    <key>Identifier</key>
                    <string>com.apple.screensharing.agent</string>
                    <key>CodeRequirement</key>
                    <string>identifier "com.apple.screensharing.agent" and anchor apple</string>
                    <key>Authorization</key>
                    <string>Allow</string>
                    <key>AuthorizationValue</key>
                    <integer>1</integer>
                    <key>Services</key>
                    <dict>
                      <key>ScreenCapture</key>
                      <true/>
                      <key>Accessibility</key>
                      <true/>
                    </dict>
                  </dict>
                </dict>
              </dict>
            </array>
            <key>PayloadType</key>
            <string>Configuration</string>
            <key>PayloadVersion</key>
            <integer>1</integer>
            <key>PayloadIdentifier</key>
            <string>com.example.screensharingprofile</string>
            <key>PayloadUUID</key>
            <string>$PROFILE_UUID</string>
            <key>PayloadDisplayName</key>
            <string>Screen Sharing Permissions Profile</string>
          </dict>
          </plist>
          EOF

          echo "Installing Screen Sharing PPPC profile..."
          sudo profiles install -path ./screensharing-pppc.mobileconfig

          echo "Restarting Remote Management to apply changes..."
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart -agent -console

      - name: Enable Remote Management and VNC legacy
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -allowAccessFor -allUsers -privs -all
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvnclegacy -vnclegacy yes
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate

      - name: Create new user 'vncuser' with password 'pass'
        run: |
          sudo sysadminctl -addUser vncuser -password pass -home /Users/vncuser -admin
          sudo mkdir -p /Users/vncuser/Desktop
          sudo chown -R vncuser:staff /Users/vncuser
          
      - name: Set VNC password for new user
        run: |
          echo "pass" | /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvncpw -vncpw -

      - name: Start Screen Sharing (VNC) service
        run: |
          sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.screensharing.plist

      - name: Create frpc.ini
        run: |
          cat > frpc.ini <<EOF
          [common]
          server_addr = ${{ secrets.IP }}
          server_port = 1234

          [vnc]
          type = tcp
          local_ip = 127.0.0.1
          local_port = 5900
          remote_port = 15900
          EOF

      - name: Show frpc.ini (debug)
        run: cat frpc.ini

      - name: Start frpc and block forever
        run: |
          echo "Starting frpc tunnel for VNC..."
          frpc -c frpc.ini
