name: macOS VNC via FRP with custom port forwarding

on:
  push:
    branches:
      - main

jobs:
  macos-vnc:
    runs-on: macos-latest

    steps:
      - name: Install frpc
        run: brew install frpc

      - name: Disable Spotlight indexing
        run: sudo mdutil -i off -a

      - name: Create VNC user and home
        run: |
          sudo dscl . -create /Users/vncuser
          sudo dscl . -create /Users/vncuser UserShell /bin/bash
          sudo dscl . -create /Users/vncuser RealName "VNC User"
          sudo dscl . -create /Users/vncuser UniqueID 1001
          sudo dscl . -create /Users/vncuser PrimaryGroupID 80
          sudo dscl . -create /Users/vncuser NFSHomeDirectory /Users/vncuser
          sudo dscl . -passwd /Users/vncuser vncpass
          sudo createhomedir -c -u vncuser > /dev/null

      - name: Reset and enable Remote Management with VNC legacy mode and password
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -deactivate -stop
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate -configure -access -on -privs -all -users vncuser \
            -clientopts -setvnclegacy -vnclegacy yes \
            -clientopts -setvncpw -vncpw vncpass \
            -restart -agent

      - name: Create frpc.ini
        run: |
          cat > frpc.ini <<EOF
          [common]
          server_addr = ${{ secrets.IP }}
          server_port = 1234

          [vnc]
          type = tcp
          local_ip = 127.0.0.1
          local_port = 5900
          remote_port = 5900
          EOF

      - name: Show frpc.ini
        run: cat frpc.ini

      - name: Start frpc
        run: frpc -c frpc.ini
