name: macOS VNC with Dummy User and FRP Tunnel

on:
  push:
    branches:
      - main

jobs:
  macos-vnc:
    runs-on: macos-latest

    steps:
      - name: Install frpc
        run: brew install frpc

      - name: Create dummy macOS user for VNC
        run: |
          sudo sysadminctl -addUser vncuser -password vncpass -admin
          sudo dscl . -create /Users/vncuser IsHidden 1

      - name: Restart and enable Apple Remote Management with VNC access
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -deactivate -stop

          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate -configure -access -on -privs -all -users vncuser \
            -clientopts -setvnclegacy -vnclegacy yes \
            -clientopts -setvncpw -vncpw vncpass \
            -restart -agent

      - name: Create frpc.ini
        run: |
          cat > frpc.ini <<EOF
          [common]
          server_addr = ${{ secrets.IP }}
          server_port = 1234

          [vnc]
          type = tcp
          local_ip = 127.0.0.1
          local_port = 5900
          remote_port = 5900
          EOF

      - name: Show frpc.ini
        run: cat frpc.ini

      - name: Start frpc tunnel
        run: frpc -c frpc.ini
