name: macOS VNC via FRP

on:
  push:
    branches:
      - main

jobs:
  macos-vnc:
    runs-on: macos-latest

    steps:
      - name: Install frpc
        run: brew install frpc

      - name: Disable Spotlight indexing
        run: sudo mdutil -i off -a

      - name: Create VNC user and home
        run: |
          sudo dscl . -create /Users/vncuser
          sudo dscl . -create /Users/vncuser UserShell /bin/bash
          sudo dscl . -create /Users/vncuser RealName "VNC User"
          sudo dscl . -create /Users/vncuser UniqueID 1001
          sudo dscl . -create /Users/vncuser PrimaryGroupID 80
          sudo dscl . -create /Users/vncuser NFSHomeDirectory /Users/vncuser
          sudo dscl . -passwd /Users/vncuser vncpass
          sudo createhomedir -c -u vncuser > /dev/null

      - name: Enable VNC and legacy password mode
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -allowAccessFor -allUsers -privs -all
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -clientopts -setvnclegacy -vnclegacy yes

      - name: Set VNC password (legacy Apple encrypted format)
        run: |
          echo vncpass | perl -we '
            BEGIN { @k = unpack "C*", pack "H*", "1734516E8BA8C5E2FF1C39567390ADCA"};
            $_ = <>; chomp; s/^(.{8}).*/$1/;
            @p = unpack "C*", $_;
            foreach (@k) { printf "%02X", $_ ^ (shift @p || 0) };
            print "\n"
          ' | sudo tee /Library/Preferences/com.apple.VNCSettings.txt

      - name: Restart Remote Management agent
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart -agent -console
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate

      - name: Create frpc.ini
        run: |
          cat > frpc.ini <<EOF
          [common]
          server_addr = ${{ secrets.IP }}
          server_port = 1234

          [vnc]
          type = tcp
          local_ip = 127.0.0.1
          local_port = 5900
          remote_port = 5900
          EOF

      - name: Show frpc.ini
        run: cat frpc.ini

      - name: Start frpc
        run: frpc -c frpc.ini
