name: macOS TigerVNC + FRPC (experimental)

on: [push]

jobs:
  macos-tigervnc-frpc:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install TigerVNC server and frpc
        run: |
          brew update
          brew install tiger-vnc
          brew install frpc
          vncserver -version || echo "vncserver command not found"
          frpc --version

      - name: Set VNC password
        run: |
          mkdir -p ~/.vnc
          echo "password" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd

      - name: Start VNC server on :1
        run: |
          vncserver :1 -geometry 1280x800 -depth 24 || echo "Failed to start VNC server (expected on macOS runner)"

      - name: Create frpc.ini
        run: |
          cat > frpc.ini <<EOF
          [common]
          server_addr = ${{ secrets.IP }}
          server_port = 1234

          [vnc]
          type = tcp
          local_ip = 127.0.0.1
          local_port = 5901
          remote_port = 15900
          EOF

      - name: Show frpc.ini
        run: cat frpc.ini

      - name: Start frpc and block forever
        run: |
          echo "Starting frpc to expose VNC port..."
          frpc -c frpc.ini
