name: Enable Apple VNC with user restriction (runner & root) and FRP tunnel

on:
  push:
    branches:
      - main

jobs:
  vnc-tunnel:
    runs-on: macos-latest

    steps:
      - name: Install frpc
        run: brew install frpc

      - name: Enable Apple Remote Management with VNC password and user access
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate -configure -access -on -privs -all -users runner,root \
            -clientopts -setvnclegacy -vnclegacy yes \
            -clientopts -setvncpw -vncpw vncpass \
            -restart -agent

      - name: Create frpc.ini
        run: |
          cat > frpc.ini <<EOF
          [common]
          server_addr = ${{ secrets.IP }}
          server_port = 1234

          [vnc]
          type = tcp
          local_ip = 127.0.0.1
          local_port = 5900
          remote_port = 5900
          EOF

      - name: Show frpc.ini
        run: cat frpc.ini

      - name: Run frpc client
        run: frpc -c frpc.ini
