name: VNC with FRPC Tunnel

on: [push]

jobs:
  vnc-frp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download and install FRPC first
        run: |
          wget https://github.com/fatedier/frp/releases/download/v0.63.0/frp_0.63.0_linux_amd64.tar.gz
          tar -xzf frp_0.63.0_linux_amd64.tar.gz
          sudo mv frp_0.63.0_linux_amd64/frpc /usr/local/bin/
          chmod +x /usr/local/bin/frpc
          frpc --version  # Confirm it's installed

      - name: Install Desktop and VNC
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies tigervnc-standalone-server

      - name: Set VNC password
        run: |
          mkdir -p ~/.vnc
          echo "password" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd

      - name: Start VNC server
        run: |
          vncserver :1 -geometry 1280x800 -depth 24

      - name: Create frpc.ini
        run: |
          cat > frpc.ini <<EOF
          [common]
          server_addr = ${{ secrets.IP }}
          server_port = 1234

          [vnc]
          type = tcp
          local_ip = 127.0.0.1
          local_port = 5901
          remote_port = 15900
          EOF

      - name: Show frpc.ini (debug)
        run: cat frpc.ini

      - name: Start frpc and block forever
        run: |
          echo "VNC is now exposed via FRP at ${{ secrets.IP }}:15900"
          frpc -c frpc.ini
